#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : azure-synapse-nspkg
Version  : 1.0.0
Release  : 2
URL      : https://files.pythonhosted.org/packages/be/fa/4315f2a270d0f50e57b18b94183406cb995b102d98017aa001b51a6e966c/azure-synapse-nspkg-1.0.0.zip
Source0  : https://files.pythonhosted.org/packages/be/fa/4315f2a270d0f50e57b18b94183406cb995b102d98017aa001b51a6e966c/azure-synapse-nspkg-1.0.0.zip
Summary  : Microsoft Azure Synapse Namespace Package [Internal]
Group    : Development/Tools
License  : MIT
Requires: azure-synapse-nspkg-python = %{version}-%{release}
Requires: azure-synapse-nspkg-python3 = %{version}-%{release}
Requires: azure-nspkg
BuildRequires : azure-nspkg
BuildRequires : buildreq-distutils3

%description
This is the Microsoft Azure Synapse namespace package.
        
        This package is not intended to be installed directly by the end user.
        
        It provides the necessary files for other packages to extend the
        azure.synapse namespace.

%package python
Summary: python components for the azure-synapse-nspkg package.
Group: Default
Requires: azure-synapse-nspkg-python3 = %{version}-%{release}

%description python
python components for the azure-synapse-nspkg package.


%package python3
Summary: python3 components for the azure-synapse-nspkg package.
Group: Default
Requires: python3-core
Provides: pypi(azure_synapse_nspkg)
Requires: pypi(azure_nspkg)

%description python3
python3 components for the azure-synapse-nspkg package.


%prep
%setup -q -n azure-synapse-nspkg-1.0.0
cd %{_builddir}/azure-synapse-nspkg-1.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1607992708
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
